-- Question 1
-- How many total orders are recorded in the sales table?

SELECT COUNT(*) AS total_orders
FROM sales;

-- Question 2
-- List all unique product categories from the products table

SELECT DISTINCT(category) AS unique_product_categories
FROM products;

-- Question 3
-- How many customers are registered in the dataset?

SELECT COUNT(*) AS registered_customers
FROM customers;

-- Question 4
-- List all stores and the cities they are located in

SELECT store_name, city
FROM stores
GROUP BY store_name, city
ORDER BY LENGTH(store_name), store_name;

-- Question 5
-- Which products have a cocoa percentage greater than 70%?

SELECT *
FROM products
WHERE cocoa_percent > 70;

-- Question 6
-- How many products does each brand offer? List brands and their product count

SELECT brand, COUNT(product_name) AS products
FROM products
GROUP BY 1
ORDER BY 1;

-- Question 7
-- Find all sales where a discount was applied (discount > 0)

SELECT *
FROM sales
WHERE discount > 0;

-- Question 8
-- What is the total revenue generated across all sales?

SELECT SUM(revenue) AS total_revenue
FROM sales;

-- Question 9
-- What is the total profit made from all orders?

SELECT SUM(profit) AS total_profit
FROM sales;

-- Question 10
-- What is the minimum and maximum profit from a single order?

SELECT MIN(profit) min_profit, MAX(profit) max_profit
FROM sales;

-- Question 11
-- What is the total quantity sold per product category?

SELECT p.category, SUM(s.quantity) AS quantity_sold
FROM products p
INNER JOIN sales s ON s.product_id = p.product_id
GROUP BY 1
ORDER BY 1;

-- Question 12
-- Show the store name, city, and total revenue for each store

SELECT st.store_name, st.city,
	SUM(s.revenue) AS total_revenue
FROM stores st
INNER JOIN sales s ON s.store_id = st.store_id
GROUP BY 1, 2
ORDER BY LENGTH(st.store_name), st.store_name;

-- Question 13
-- Which brand generates the highest total profit?

SELECT p.brand, SUM(s.profit) AS highest_total_profit
FROM products p
INNER JOIN sales s ON s.product_id = p.product_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

-- Question 14
-- Which country generates the most total revenue?

SELECT st.country, SUM(s.revenue) AS total_revenue
FROM stores st
INNER JOIN sales s ON s.store_id = st.store_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

-- Question 15
-- What is the total revenue generated by loyalty members vs non-loyalty members?

SELECT c.loyalty_member, SUM(s.revenue) AS total_revenue,
CASE
	WHEN loyalty_member = 1 THEN 'loyalty_member'
ELSE 'Non_loyalty_member' END AS status
FROM customers c
INNER JOIN sales s ON s.customer_id = c.customer_id
GROUP BY 1, 3
ORDER BY 2 DESC;

-- Question 16
-- List the top 5 products by total quantity sold, including the product name and brand

SELECT p.product_name, p.brand, 
SUM(s.quantity) AS total_quantity
FROM products p
INNER JOIN sales s ON s.product_id = p.product_id
GROUP BY 1, 2
ORDER BY 3 DESC;

-- Question 17
-- Which store type (retail, online, etc.) generates the most revenue?

SELECT st.store_type, SUM(s.revenue) AS total_revenue
FROM stores st
INNER JOIN sales s ON s.store_id = st.store_id
GROUP BY 1
ORDER BY DESC;

-- Question 18
-- What is the average order revenue for male vs female customers?

SELECT c.gender, AVG(s.revenue) AS average_revenue
FROM customers c
INNER JOIN sales s ON s.customer_id = c.customer_id
GROUP BY 1
ORDER BY 2 DESC;

-- Question 19
-- Which city has the highest number of orders placed?

SELECT st.city, COUNT(s.order_id) AS total_order
FROM stores st
INNER JOIN sales s ON s.store_id = st.store_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

-- Question 20
-- List the products that have a unit price greater than the average unit price across all products

SELECT DISTINCT p.product_name
FROM products p
INNER JOIN sales s ON s.product_id = p.product_id
WHERE s.unit_price > (SELECT 
AVG(unit_price) FROM sales)
ORDER BY 1;


























































